<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    //
    $products = [
      [
        'name' => 'Abacate',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'abacate.png',
      ],
      [
        'name' => 'Abacaxi',
        'price' => 1.49,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'abacaxi.png',
      ],
      [
        'name' => 'Abóbora',
        'price' => 1.99,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'abobora.png',
      ],
      [
        'name' => 'Abobrinha',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'abobrinha.png',
      ],
      [
        'name' => 'Agrião',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'verdura',
        'image' => 'agriao.png',
      ],
      [
        'name' => 'Alecrim',
        'price' => 0.79,
        'unit' => 'unidade',
        'category' => 'tempero',
        'image' => 'alecrim.png',
      ],
      [
        'name' => 'Alface',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'verdura',
        'image' => 'alface.png',
      ],
      [
        'name' => 'Alho Roxo',
        'price' => 0.69,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'alho-roxo.png',
      ],
      [
        'name' => 'Ameixa',
        'price' => 1.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'ameixa.png',
      ],
      [
        'name' => 'Banana',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'banana.png',
      ],
      [
        'name' => 'Batata-Doce',
        'price' => 1.49,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'batata-doce.png',
      ],
      [
        'name' => 'Batata Inglesa',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'batata-inglesa.png',
      ],
      [
        'name' => 'Berinjela',
        'price' => 1.79,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'berinjela.png',
      ],
      [
        'name' => 'Beterraba',
        'price' => 1.09,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'beterraba.png',
      ],
      [
        'name' => 'Blueberry',
        'price' => 2.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'blueberry.png',
      ],
      [
        'name' => 'Brócolis',
        'price' => 1.69,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'brocolis.png',
      ],
      [
        'name' => 'Caju',
        'price' => 2.49,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'caju.png',
      ],
      [
        'name' => 'Caqui',
        'price' => 1.79,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'caqui.png',
      ],
      [
        'name' => 'Cebola Roxa',
        'price' => 0.89,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'cebola-roxa.png',
      ],
      [
        'name' => 'Cebola',
        'price' => 0.59,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'cebola.png',
      ],
      [
        'name' => 'Cebolinha',
        'price' => 0.79,
        'unit' => 'unidade',
        'category' => 'tempero',
        'image' => 'cebolinha.png',
      ],
      [
        'name' => 'Cenoura',
        'price' => 0.79,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'cenoura.png',
      ],
      [
        'name' => 'Chuchu',
        'price' => 0.89,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'chuchu.png',
      ],
      [
        'name' => 'Coco',
        'price' => 1.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'coco.png',
      ],
      [
        'name' => 'Coentro',
        'price' => 0.69,
        'unit' => 'unidade',
        'category' => 'tempero',
        'image' => 'coentro.png',
      ],
      [
        'name' => 'Couve Flor',
        'price' => 2.49,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'couve-flor.png',
      ],
      [
        'name' => 'Couve',
        'price' => 0.89,
        'unit' => 'unidade',
        'category' => 'verdura',
        'image' => 'couve.png',
      ],
      [
        'name' => 'Espinafre',
        'price' => 0.79,
        'unit' => 'unidade',
        'category' => 'verdura',
        'image' => 'espinafre.png',
      ],
      [
        'name' => 'Figo',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'figo.png',
      ],
      [
        'name' => 'Framboesa',
        'price' => 2.49,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'framboesa.png',
      ],
      [
        'name' => 'Gengibre',
        'price' => 1.39,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'gengibre.png',
      ],
      [
        'name' => 'Goiaba',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'goiaba.png',
      ],
      [
        'name' => 'Graviola',
        'price' => 2.19,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'graviola.png',
      ],
      [
        'name' => 'Hortelã',
        'price' => 0.69,
        'unit' => 'unidade',
        'category' => 'tempero',
        'image' => 'hortela.png',
      ],
      [
        'name' => 'Inhame',
        'price' => 1.09,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'inhame.png',
      ],
      [
        'name' => 'Jiló',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'jilo.png',
      ],
      [
        'name' => 'Kiwi',
        'price' => 1.79,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'kiwi.png',
      ],
      [
        'name' => 'Laranja',
        'price' => 0.79,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'laranja.png',
      ],
      [
        'name' => 'Limão',
        'price' => 0.69,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'limao.png',
      ],
      [
        'name' => 'Maçã Verde',
        'price' => 1.09,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'maca-verde.png',
      ],
      [
        'name' => 'Maçã',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'maca.png',
      ],
      [
        'name' => 'Mamão',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'mamao.png',
      ],
      [
        'name' => 'Manga',
        'price' => 1.79,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'manga.png',
      ],
      [
        'name' => 'Manjericão',
        'price' => 0.89,
        'unit' => 'unidade',
        'category' => 'tempero',
        'image' => 'manjericao.png',
      ],
      [
        'name' => 'Maracujá',
        'price' => 1.39,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'maracuja.png',
      ],
      [
        'name' => 'Melancia',
        'price' => 2.49,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'melancia.png',
      ],
      [
        'name' => 'Melão',
        'price' => 2.09,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'melao.png',
      ],
      [
        'name' => 'Milho',
        'price' => 0.69,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'milho.png',
      ],
      [
        'name' => 'Morango',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'morango.png',
      ],
      [
        'name' => 'Pepino',
        'price' => 0.99,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'pepino.png',
      ],
      [
        'name' => 'Pera',
        'price' => 1.09,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'pera.png',
      ],
      [
        'name' => 'Pêssego',
        'price' => 1.29,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'pessego.png',
      ],
      [
        'name' => 'Pimenta Cumari',
        'price' => 1.49,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'pimenta-cumari.png',
      ],
      [
        'name' => 'Pimentão Amarelo',
        'price' => 1.79,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'pimentao-amarelo.png',
      ],
      [
        'name' => 'Pimentão Verde',
        'price' => 1.69,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'pimentao-verde.png',
      ],
      [
        'name' => 'Pimentão Vermelho',
        'price' => 1.69,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'pimentao-vermelho.png',
      ],
      [
        'name' => 'Pinha',
        'price' => 1.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'pinha.png',
      ],
      [
        'name' => 'Pitaya',
        'price' => 6.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'pitaya.png',
      ],
      [
        'name' => 'Quiabo',
        'price' => 2.99,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'quiabo.png',
      ],
      [
        'name' => 'Repolho Roxo',
        'price' => 1.49,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'repolho-roxo.png',
      ],
      [
        'name' => 'Repolho Verde',
        'price' => 1.39,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'repolho-verde.png',
      ],
      [
        'name' => 'Salsinha',
        'price' => 0.99,
        'unit' => 'maço',
        'category' => 'tempero',
        'image' => 'salsinha.png',
      ],
      [
        'name' => 'Tangerina',
        'price' => 1.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'tangerina.png',
      ],
      [
        'name' => 'Tomate',
        'price' => 1.19,
        'unit' => 'unidade',
        'category' => 'vegetal',
        'image' => 'tomate.png',
      ],
      [
        'name' => 'Uva Thompson',
        'price' => 4.99,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'uva-thompson.png',
      ],
      [
        'name' => 'Uva Vitória',
        'price' => 4.79,
        'unit' => 'unidade',
        'category' => 'fruta',
        'image' => 'uva-vitoria.png',
      ],
    ];

    DB::table('products')->insert($products);
  }
}
